CREATE TABLE CUSTOMER_INVITATION(
"INVITATION_CODE" VARCHAR2(20) NOT NULL,
"EMAIL" VARCHAR2(100) NOT NULL,
"CREATED_BY" VARCHAR2(50) NOT NULL,
"LAST_UPDATED_BY" VARCHAR2(50) NOT NULL,
"CREATION_TIME" TIMESTAMP NOT NULL,
"LAST_UPDATED_TIME" TIMESTAMP NOT NULL
)

CREATE TABLE CUSTOMER_PROFILE(
"PROFILE_ID" CHAR(32) NOT NULL,
"EMAIL" VARCHAR2(100) NOT NULL,
"CREATED_BY" VARCHAR2(50) NOT NULL,
"LAST_UPDATED_BY" VARCHAR2(50) NOT NULL,
"CREATION_TIME" TIMESTAMP NOT NULL,
"LAST_UPDATED_TIME" TIMESTAMP NOT NULL
)

CREATE TABLE SME_PROFILE(
"PROFILE_ID" CHAR(32) NOT NULL,
"COMPANY_NAME_CHN" VARCHAR2(50) NOT NULL,
"COMPANY_NAME_ENG" VARCHAR2(50) NOT NULL,
"CREATED_BY" VARCHAR2(50) NOT NULL,
"LAST_UPDATED_BY" VARCHAR2(50) NOT NULL,
"CREATION_TIME" TIMESTAMP NOT NULL,
"LAST_UPDATED_TIME" TIMESTAMP NOT NULL
);
