server:
    port: 8080
    servlet:
        context-path: /eportal-service
spring:
    application:
        name: eportal-service
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:eportaldb
        username: sa
    h2:
        console:
            enabled: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
