server:
  port: 8080
  servlet:
    context-path: /

serai:
  companyTypes:
    - type: Sole proprietorship
      score: 12
    - type: Limited Liability Company
      score: 63
    - type: Partnership
      score: 75
    - type: Others
      score: 0
  numOfEmployees:
    - from: 1
      to: 5
      score: 0
    - from: 6
      to: 10
      score: 20
    - from: 11
      to: 15
      score: 32
    - from: 16
      to: 20
      score: 55
    - from: 21
      to:
      score: 70
  timeInBusinesses:
    - from: 0
      to: 3
      score: 0
    - from: 4
      to: 9
      score: 28
    - from: 10
      to: 15
      score: 36
    - from: 16
      to:
      score: 59
