DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS SME_PROFILE;

CREATE TABLE CUSTOMER (
    RECORD_ID CHAR(36) NOT NULL,
    INVITATION_CODE VARCHAR2(20) NOT NULL,
    INVITATION_CODE_EXPIRY_TIME TIMESTAMP NOT NULL,
    EMAIL VARCHAR2(70) NOT NULL,
    PROFILE_ID VARCHAR2(20),
    CREATED_BY VARCHAR2(50) NOT NULL,
    LAST_UPDATED_BY VARCHAR2(50) NOT NULL,
    CREATION_TIME TIMESTAMP NOT NULL,
    LAST_UPDATED_TIME TIMESTAMP NOT NULL
);

CREATE TABLE SME_PROFILE(
    RECORD_ID CHAR(36) NOT NULL,
    PROFILE_ID VARCHAR2(20) NOT NULL,
    COMPANY_NAME_ENG VARCHAR2(100) NOT NULL,
    COMPANY_NAME_CHN VARCHAR2(50) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_BY VARCHAR2(50) NOT NULL,
    LAST_UPDATED_BY VARCHAR2(50) NOT NULL,
    CREATION_TIME TIMESTAMP NOT NULL,
    LAST_UPDATED_TIME TIMESTAMP NOT NULL
);

INSERT INTO CUSTOMER(RECORD_ID, INVITATION_CODE, INVITATION_CODE_EXPIRY_TIME, EMAIL, PROFILE_ID, CREATED_BY, LAST_UPDATED_BY, CREATION_TIME, LAST_UPDATED_TIME)
VALUES (RANDOM_UUID(), '1', SYSDATE+30, 'abc@email.com', '2', 'SYSTEM', 'SYSTEM', SYSDATE, SYSDATE);

INSERT INTO SME_PROFILE(RECORD_ID, PROFILE_ID, COMPANY_NAME_ENG, COMPANY_NAME_CHN, STATUS, CREATED_BY, LAST_UPDATED_BY, CREATION_TIME, LAST_UPDATED_TIME)
VALUES (RANDOM_UUID(), '2', 'comp name eng', 'comp name chn', 'DRAFT', 'SYSTEM', 'SYSTEM', SYSDATE, SYSDATE);
